# Generated by Django 3.1.7 on 2021-07-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210701_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainders',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
