# Generated by Django 3.1.7 on 2021-07-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remainders_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainders',
            name='count',
        ),
    ]
