# Generated by Django 3.1.7 on 2021-07-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_remainders_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainders',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
